export const ADD_USER = 'ADD_USER';
export const UPDATE_USER = 'UPDATE_USER';

export const ADD_GYM = 'ADD_GYM';
export const UPDATE_GYM = 'UPDATE_GYM';

export const ADD_WORKOUT = 'ADD_WORKOUT';
export const DELETE_WORKOUT = 'DELETE_WORKOUT';
export const ADD_ALLWORKOUTS = 'ADD_ALLWORKOUTS';

export const ADD_RESERVATION = 'ADD_RESERVATION';
export const DELETE_RESERVATION = 'DELETE_RESERVATION';
export const ADD_ALLRESERVATIONS = 'ADD_ALLRESERVATIONS';

export const ADD_USERINGYM = 'ADD_USERINGYM';
export const DELETE_USERFROMGYM = 'DELETE_USERFROMGYM';
export const ADD_ALLUSERSINGYM = 'ADD_ALLUSERSINGYM';
